# Generated by Django 4.0 on 2021-12-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
