# Generated by Django 4.0 on 2021-12-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
